// blogs-react/src/components/app/App.jsx
import React from 'react';
import { Route, Routes, NavLink } from 'react-router-dom';
import { Blogs } from '../blogs/Blogs';
import { BlogDetail } from '../blog-detail/blog-detail';
import './App.css';

export function App() {
  return (
    <div className="App">
      <header>
        <nav>
          <menu>
            <li>
              <NavLink to="/">Home</NavLink>
            </li>
            <li>
              <NavLink to="/blogs">Blogs</NavLink>
            </li>
          </menu>
        </nav>
      </header>
      <main>
        <Routes>
          <Route path='/blogs' element={<Blogs />} />
          <Route path='/blogs/:id' element={<BlogDetail />} />
          <Route path='/' element={<h1>This is Home</h1>} />
        </Routes>
      </main>
      <footer>
        <small>&copy; {new Date().getFullYear()} all rights reserved</small>
      </footer>
    </div>
  );
}

// blogs-ng/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'blogs-ng';
}

<div class="app">
  <header class="header">
    <nav class="navbar">
      <a routerLink="" class="logo">Witer</a>
      <menu class="nav" role="menu">
        <li class="nav-item" role="menuitem"><a routerLink="" class="nav-link">Home</a></li>
        <li class="nav-item" role="menuitem"><a routerLink="/blogs" class="nav-link">Blogs <span>{{ count }}</span> | <span>{{ blogsCount$ | async }}</span></a></li>
        <li class="nav-item" role="menuitem"><a routerLink="/auth/register" class="nav-link">Register</a></li>
      </menu>
    </nav>
  </header>
  <main>
    <router-outlet></router-outlet>
  </main>
  <footer class="footer">
    <small>&copy; all rights reserved</small>
  </footer>
</div>
